/* This file is auto-generated by FOXJAR. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

/// <reference path="../../../foxjar-env.d.ts" />

import "foxjar"
export {}
